version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: poetry run gunicorn --bind 0.0.0.0:8000 server.wsgi
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - DEBUG=True